FROM ubuntu:noble

ENV VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

ARG TARGETOS
ARG TARGETARCH
ARG BUILDPLATFORM
ARG TARGETPLATFORM

RUN echo "##### target arch= ${TARGETARCH}"
RUN echo "##### target platform = ${TARGETPLATFORM}"

