name: Get latest develop commit
on:
  schedule:
    - cron:  '0 23 * * *'
  workflow_dispatch:
  
jobs:
  get-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/${GITHUB_REPOSITORY_OWNER}/calibre-web/branches | \
          jq -r ".[] | select(.name==\"develop\") | .commit.sha" > latest-develop-commit.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Release Bot'
          git config --global user.email 'releasebot@iamdixon.net'
          git commit -am "New release version"
          git push
