name: Get latest develop commit
on:
  schedule:
    - cron:  '0 23 * * *'  
  workflow_dispatch:
jobs:
  get-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/nigeldixon/calibre-web/branches | \
          jq -r ".[] | select(.name==\"develop\") | .commit.sha" > latest-develop-commit.txt
      - name: Force changes
        run: touch change.temp
      - name: Current checksum
        run: cat latest-develop-commit.txt
      - name: Show has changes
        run: echo $([ -z "git status --porcelain" ] && echo "0" || echo "1")
      - name: Check for modified files
        id: changes
        run: echo "modified=$([ -z "git status --porcelain" ] && echo "0" || echo "1")" >> $GITHUB_OUTPUT
      - name: Show if changes
        run: echo "Has changes ${{ steps.changes.outputs.changed }}"
      - name: Process changes
        if: steps.changes.outputs.changed == 1
        run: |
          git config --global user.name 'Release Bot'
          git config --global user.email 'releasebot@iamdixon.net'
          git commit -am "New commits to develop branch"
          git push
