name: Get latest develop commit
on:
  schedule:
    - cron:  '0 23 * * *'  
  workflow_dispatch:
jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs: 
      needsdeploy: ${{ steps.changes.outputs.modified }}
    steps:
      - uses: actions/checkout@v4
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/nigeldixon/calibre-web/branches | \
          jq -r ".[] | select(.name==\"develop\") | .commit.sha" > latest-develop-commit.txt
      - name: Process changes
        id: changes
        run: |
          git config --global user.name 'Release Bot'
          git config --global user.email 'releasebot@iamdixon.net'
          git commit -am "New commits to develop branch" && modified=1 || modified=0 
          echo "modified=$modified" >> $GITHUB_OUTPUT
          echo "$GITHUB_OUTPUT"
          git push
      - name: Show if changes
        run: echo "Has changes ${{ steps.changes.outputs.modified }}"
  deploy:
    needs: get-version
    if: needs.get-version.outputs.needsdeploy == 1
    uses: ./.github/workflows/docker-publish.yml
