name: Get latest develop commit
on:
  schedule:
    - cron:  '0 23 * * *'  
  workflow_dispatch:
jobs:
  get-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/${GITHUB_REPOSITORY_OWNER}/calibre-web/branches | \
          jq -r ".[] | select(.name==\"develop\") | .commit.sha" > latest-develop-commit.txt
      - name: Check for modified files
        id: changes
        run: echo "{modified}={$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")}" >> $GITHUB_OUTPUT
      - name: Process changes
        if: steps.changes.outputs.changed == 1
        run: |
          git config --global user.name 'Release Bot'
          git config --global user.email 'releasebot@iamdixon.net'
          git commit -am "New commits to develop branch"
          git push
